// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {}
  }
  "/react-query": {
    params: {}
  }
  "/about": {
    params: {}
  }
}

type RouteFiles = {
  "root.tsx": {
    id: "root"
    page: "/" | "/react-query" | "/about"
  }
  "./routes/home.tsx": {
    id: "routes/home"
    page: "/"
  }
  "./routes/react-query-demo.tsx": {
    id: "routes/react-query-demo"
    page: "/react-query"
  }
  "./routes/about.tsx": {
    id: "routes/about"
    page: "/about"
  }
}

type RouteModules = {
  "root": typeof import("./app/root.tsx")
  "routes/home": typeof import("./app/./routes/home.tsx")
  "routes/react-query-demo": typeof import("./app/./routes/react-query-demo.tsx")
  "routes/about": typeof import("./app/./routes/about.tsx")
}
