packages:
  - apps/*
  - packages/*/*
  - '!packages/*/dist'
  - '!packages/*/*/dist'

catalog:
  '@astrojs/starlight': 0.36.0
  '@astrojs/starlight-tailwind': 4.0.1
  '@biomejs/biome': 2.1.3
  '@nx/js': 22.0.1
  '@nx/node': 22.0.1
  '@nx/vite': 22.0.1
  '@nx/web': 22.0.1
  '@nx/react': 22.0.1
  '@react-router/dev': 7.9.2
  '@swc-node/register': 1.9.1
  '@swc/core': 1.5.7
  '@swc/helpers': 0.5.11
  '@types/react': 19.0.0
  '@types/react-dom': 19.0.0
  '@vitejs/plugin-react': 4.3.3
  jsdom: 22.1.0
  prettier: 2.6.2
  '@corvu/drawer': 0.2.4
  '@effect/build-utils': 0.7.7
  '@effect/cli': 0.70.0
  '@effect/language-service': 0.41.0
  '@effect/platform': 0.91.1
  '@effect/platform-bun': 0.97.1
  '@effect/platform-node': 0.97.1
  '@effect/vitest': 0.25.0
  "@effect-atom/atom": "0.3.2"
  '@kobalte/core': 0.13.11
  '@prisma/client': 6.12.0
  '@prisma/generator-helper': 6.12.0
  '@prisma/internals': 6.12.0
  '@radix-ui/react-form': 0.1.8
  '@radix-ui/react-label': 2.1.7
  '@radix-ui/react-slot': 1.2.3
  '@remix-run/node': 2.17.1
  '@remix-run/node-fetch-server': 0.8.0
  '@remix-run/react': 2.17.1
  '@remix-run/serve': 2.17.1
  '@solidjs/start': 1.2.0
  '@tailwindcss/postcss': 4.1.13
  '@tailwindcss/typography': 0.5.16
  '@tailwindcss/vite': 4.1.13
  '@tanstack/query-core': 5.90.2
  '@tanstack/react-form': 1.23.4
  '@tanstack/react-query': 5.90.2
  '@tanstack/react-query-devtools': 5.90.2
  '@tanstack/react-router': 1.132.7
  '@tanstack/react-router-devtools': 1.132.7
  '@tanstack/router-plugin': 1.132.7
  '@tanstack/solid-form': 1.23.4
  '@tanstack/solid-query': 5.90.3
  '@tanstack/solid-query-devtools': 5.90.3
  '@tanstack/solid-router': 1.132.7
  '@tanstack/solid-router-devtools': 1.132.7
  '@tanstack/solid-start': 1.132.9
  '@testing-library/dom': 10.4.1
  '@testing-library/react': 16.3.0
  '@types/better-sqlite3': 7.6.13
  '@types/compression': 1.8.1
  '@types/express': 5.0.3
  '@types/node': 20.0.0
  '@types/validator': 13.15.3
  '@react-router/node': 7.9.2
  '@react-router/serve': 7.9.2
  'isbot': 4.4.0
  'bun': 1.3.0
  '@vitejs/plugin-rsc': 0.4.11
  '@testing-library/jest-dom': 6.7.0
  '@solidjs/testing-library': 0.8.6
  'prisma-effect-kysely': 1.9.2
  astro: 5.14.1
  autoprefixer: 10.4.21
  better-auth: 1.3.18
  better-sqlite3: 12.4.1
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  compression: 1.8.0
  cross-env: 7.0.3
  effect: 3.17.14
  express: 5.1.0
  globals: 16.4.0
  globby: 14.1.0
  lucide-react: 0.544.0
  lucide-solid: 0.544.0
  postcss: 8.5.6
  prisma: 6.12.0
  react: 19.0.0
  react-dom: 19.0.0
  react-router: 7.9.2
  sharp: 0.34.4
  solid-js: 1.9.9
  starlight-sidebar-topics: 0.6.1
  starlight-sidebar-topics-dropdown: 0.5.1
  starlight-theme-nova: 0.9.5
  tailwind-merge: 3.3.1
  tailwindcss: 4.1.13
  tailwindcss-animate: 1.0.7
  tslib: 2.3.0
  tsx: 4.20.3
  tw-animate-css: 1.4.0
  typescript: 5.9.3
  validator: 13.15.15
  vite: 7.1.7
  '@vitest/ui': 3.0.0
  husky: 9.1.7
  jiti: 2.4.2
  lint-staged: 16.1.2
  nx: 22.0.1
  ts-patch: 3.3.0
  ultracite: 5.0.48
  verdaccio: 6.0.5
  vitest: 3.0.0
  vite-plugin-devtools-json: 0.2.0
  vite-plugin-dts: 4.5.4
  vite-plugin-solid: 2.11.8
  vite-tsconfig-paths: 5.1.4
  web-vitals: 5.1.0

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js
  - esbuild
  - msgpackr-extract
  - nx