packages:
  - "apps/*"
  - "packages/*/*"
  - "!packages/*/dist"
  - "!packages/*/*/dist"
catalog:
  "@astrojs/starlight": 0.36.3
  "@astrojs/starlight-tailwind": 4.0.2
  "@biomejs/biome": 2.3.7
  "@corvu/drawer": 0.2.4
  "@effect-atom/atom": 0.4.3
  "@effect/build-utils": 0.8.9
  "@effect/cli": 0.72.1
  "@effect/language-service": 0.56.0
  "@effect/platform": 0.93.3
  "@effect/platform-bun": 0.97.1
  "@effect/platform-http": 0.91.1
  "@effect/platform-node": 0.101.1
  "@effect/vitest": 0.27.0
  "@kobalte/core": 0.13.11
  "@nx/js": 22.1.1
  "@nx/node": 22.1.1
  "@nx/react": 22.1.1
  "@nx/vite": 22.1.1
  "@nx/web": 22.1.1
  "@prisma/client": 7.0.0
  "@prisma/generator-helper": 7.0.0
  "@prisma/internals": 7.0.0
  "@radix-ui/react-form": 0.1.8
  "@radix-ui/react-label": 2.1.8
  "@radix-ui/react-slot": 1.2.4
  "@react-router/dev": 7.9.6
  "@react-router/node": 7.9.6
  "@react-router/serve": 7.9.6
  "@remix-run/node": 2.17.2
  "@remix-run/node-fetch-server": 0.12.0
  "@remix-run/react": 2.17.2
  "@remix-run/serve": 2.17.2
  "@solidjs/start": 1.2.0
  "@solidjs/testing-library": 0.8.10
  "@swc-node/register": 1.11.1
  "@swc/core": 1.15.3
  "@swc/helpers": 0.5.17
  "@tailwindcss/postcss": 4.1.17
  "@tailwindcss/typography": 0.5.19
  "@tailwindcss/vite": 4.1.17
  "@tanstack/query-core": 5.90.10
  "@tanstack/react-form": 1.25.0
  "@tanstack/react-query": 5.90.10
  "@tanstack/react-query-devtools": 5.91.0
  "@tanstack/react-router": 1.139.3
  "@tanstack/react-router-devtools": 1.139.3
  "@tanstack/router-plugin": 1.139.3
  "@tanstack/solid-form": 1.25.0
  "@tanstack/solid-query": 5.90.13
  "@tanstack/solid-query-devtools": 5.91.0
  "@tanstack/solid-router": 1.139.3
  "@tanstack/solid-router-devtools": 1.139.3
  "@tanstack/solid-start": 1.139.3
  "@testing-library/dom": 10.4.1
  "@testing-library/jest-dom": 6.9.1
  "@testing-library/react": 16.3.0
  "@types/better-sqlite3": 7.6.13
  "@types/compression": 1.8.1
  "@types/express": 5.0.5
  "@types/node": 20.19.25
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  "@types/validator": 13.15.10
  "@vitejs/plugin-react": 5.1.1
  "@vitejs/plugin-rsc": 0.5.1
  "@vitest/ui": 4.0.13
  astro: 5.16.0
  autoprefixer: 10.4.22
  better-auth: 1.4.1
  better-sqlite3: 12.4.6
  bun: 1.3.3
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  compression: 1.8.1
  cross-env: 10.1.0
  effect: 3.19.6
  express: 5.1.0
  globals: 16.5.0
  globby: 16.0.0
  husky: 9.1.7
  isbot: 5.1.32
  jiti: 2.6.1
  jsdom: 27.2.0
  lint-staged: 16.2.7
  lucide-react: 0.554.0
  lucide-solid: 0.554.0
  nx: 22.1.1
  postcss: 8.5.6
  prettier: 2.8.8
  prisma: 7.0.0
  prisma-effect-kysely: 1.11.0
  react: 19.2.0
  react-dom: 19.2.0
  react-router: 7.9.6
  sharp: 0.34.5
  solid-js: 1.9.10
  starlight-sidebar-topics: 0.6.2
  starlight-sidebar-topics-dropdown: 0.5.2
  starlight-theme-nova: 0.10.0
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.17
  tailwindcss-animate: 1.0.7
  ts-patch: 3.3.0
  tslib: 2.8.1
  tsx: 4.20.6
  tw-animate-css: 1.4.0
  typescript: 5.9.3
  ultracite: 6.3.6
  validator: 13.15.23
  verdaccio: 6.2.2
  vite: 7.2.4
  vite-plugin-devtools-json: 0.4.1
  vite-plugin-dts: 4.5.4
  vite-plugin-solid: 2.11.10
  vite-tsconfig-paths: 5.1.4
  vitest: 3.2.4
  web-vitals: 5.1.0
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - "better-sqlite3"
  - "core-js"
  - "esbuild"
  - "msgpackr-extract"
  - "nx"
