packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/solid/*'
  - 'packages/react/*'
  - 'packages/node/*'
  - 'packages/chat/*'
  - 'packages/shared/*'

catalog:
  '@tanstack/solid-query': '5.90.3'
  '@kobalte/core': '0.13.11'
  'effect': '3.17.14'
  '@effect/platform': '0.91.1'
  '@effect/platform-node': '0.97.1'
  '@effect/cli': '0.70.0'
  '@effect/language-service': '0.41.0'
  'solid-js': '1.9.9'
  'class-variance-authority': '0.7.1'
  'clsx': '2.1.1'
  'tailwind-merge': '3.3.1'
  'tailwindcss-animate': '1.0.7'
  'lucide-solid': '0.544.0'
  '@corvu/drawer': '0.2.4'
  'better-auth': '1.3.18'
  'better-sqlite3': '12.4.1'
  '@types/better-sqlite3': '7.6.13'
  '@tailwindcss/vite': '4.1.13'
  '@tailwindcss/postcss': '4.1.13'
  '@tanstack/router-plugin': '1.132.7'
  '@tanstack/solid-router': '1.132.7'
  '@tanstack/solid-start': '1.132.8'
  '@solidjs/start': '1.0.13'
  '@tanstack/solid-form': '1.23.4'
  '@tanstack/solid-router-devtools': '1.132.7'
  '@tanstack/solid-query-devtools': '5.90.3'
  '@tanstack/react-query': '5.90.2'
  '@tanstack/query-core': '5.90.2'
  '@types/react': '19.1.13'
  'react': '19.1.1'
  'react-dom': '19.1.1'
  '@radix-ui/react-slot': '1.2.3'
  '@radix-ui/react-label': '2.1.7'
  '@radix-ui/react-form': '0.1.8'
  '@tanstack/react-form': '1.23.4'
  '@tanstack/react-query-devtools': '5.90.2'
  '@tanstack/react-router': '1.132.7'
  '@tanstack/react-router-devtools': '1.132.7'
  '@testing-library/dom': '10.4.1'
  '@testing-library/react': '16.3.0'
  'jsdom': '27.0.0'
  'vitest': '3.2.4'
  'web-vitals': '5.1.0'
  '@types/react-dom': '19.1.9'
  '@vitejs/plugin-react': '5.0.3'
  'globals': '16.4.0'
  'tailwindcss': '4.1.13'
  'lucide-react': '0.544.0'
  'tw-animate-css': '1.4.0'
  'autoprefixer': '10.4.21'
  '@types/validator': '13.15.3'
  'validator': '13.15.15'
  'globby': '14.1.0'
  'postcss': '8.5.6'
  'vite-tsconfig-paths': '5.1.4'
  '@biomejs/biome': '2.2.4'
  'typescript': '5.9.2'
  'tslib': '2.8.1'
  'vite': '7.1.7'
  'vite-plugin-solid': '2.11.8'
  'vite-plugin-dts': '4.5.4'
  '@astrojs/starlight': '0.36.0'
  '@astrojs/starlight-tailwind': '4.0.1'
  'starlight-theme-nova': '0.9.5'
  'starlight-sidebar-topics': '0.6.1'
  'starlight-sidebar-topics-dropdown': '0.5.1'
  'astro': '5.14.0'
  'sharp': '0.34.4'
  '@types/node': '24.5.2'
