packages:
  - apps/*
  - packages/*/*
  - '!packages/*/dist'
  - '!packages/*/*/dist'

catalog:
  '@astrojs/starlight': 0.36.0
  '@astrojs/starlight-tailwind': 4.0.1
  '@biomejs/biome': 2.2.4
  '@corvu/drawer': 0.2.4
  '@effect/cli': 0.70.0
  '@effect/language-service': 0.41.0
  '@effect/platform': 0.91.1
  '@effect/platform-node': 0.97.1
  '@kobalte/core': 0.13.11
  '@radix-ui/react-form': 0.1.8
  '@radix-ui/react-label': 2.1.7
  '@radix-ui/react-slot': 1.2.3
  '@solidjs/start': 1.2.0
  '@tailwindcss/postcss': 4.1.13
  '@tailwindcss/vite': 4.1.13
  '@tanstack/query-core': 5.90.2
  '@tanstack/react-form': 1.23.4
  '@tanstack/react-query': 5.90.2
  '@tanstack/react-query-devtools': 5.90.2
  '@tanstack/react-router': 1.132.7
  '@tanstack/react-router-devtools': 1.132.7
  '@tanstack/router-plugin': 1.132.7
  '@tanstack/solid-form': 1.23.4
  '@tanstack/solid-query': 5.90.3
  '@tanstack/solid-query-devtools': 5.90.3
  '@tanstack/solid-router': 1.132.7
  '@tanstack/solid-router-devtools': 1.132.7
  '@tanstack/solid-start': 1.132.9
  '@testing-library/dom': 10.4.1
  '@testing-library/react': 16.3.0
  '@types/better-sqlite3': 7.6.13
  '@types/node': 24.5.2
  '@types/react': 19.1.13
  '@types/react-dom': 19.1.9
  '@types/validator': 13.15.3
  '@vitejs/plugin-react': 5.0.3
  astro: 5.14.1
  autoprefixer: 10.4.21
  better-auth: 1.3.18
  better-sqlite3: 12.4.1
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  effect: 3.17.14
  globals: 16.4.0
  globby: 14.1.0
  jsdom: 27.0.0
  lucide-react: 0.544.0
  lucide-solid: 0.544.0
  postcss: 8.5.6
  react: 19.1.1
  react-dom: 19.1.1
  sharp: 0.34.4
  solid-js: 1.9.9
  starlight-sidebar-topics: 0.6.1
  starlight-sidebar-topics-dropdown: 0.5.1
  starlight-theme-nova: 0.9.5
  tailwind-merge: 3.3.1
  tailwindcss: 4.1.13
  tailwindcss-animate: 1.0.7
  tslib: 2.8.1
  tw-animate-css: 1.4.0
  typescript: 5.9.2
  validator: 13.15.15
  vite: 7.1.7
  vite-plugin-dts: 4.5.4
  vite-plugin-solid: 2.11.8
  vite-tsconfig-paths: 5.1.4
  vitest: 3.2.4
  web-vitals: 5.1.0

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js
  - esbuild
  - msgpackr-extract
  - nx