#!/usr/bin/env tsx

import { execSync } from 'node:child_process'
import fs from 'node:fs/promises'
import path from 'node:path'
import gh from '@prisma/generator-helper'

const header = `-- This file was generated by sql-schema-generator, do not edit manually.
-- Generated at: ${new Date().toISOString()}

`
type SqlGeneratorOptions = {
  generator: {
    output?: {
      value: string
    }
  }
}

export async function generateSqlSchema(options: SqlGeneratorOptions) {
  const outputDir = options.generator.output?.value || '../generated'
  const datasourceUrl = 'prisma/dev.db'

  if (!datasourceUrl) {
    throw new Error('No datasource URL found')
  }

  await fs.mkdir(outputDir, { recursive: true })

  try {
    let dbPath = datasourceUrl
    if (dbPath.startsWith('file:')) {
      dbPath = dbPath.replace('file:', '')
    }

    if (!path.isAbsolute(dbPath)) {
      dbPath = path.resolve(process.cwd(), dbPath)
    }

    const schemaOutput = execSync(`sqlite3 "${dbPath}" ".schema"`, { encoding: 'utf8' })
    const outputPath = path.join(outputDir, 'schema.sql')
    await fs.writeFile(outputPath, header + schemaOutput)
  } catch (error) {
    console.error('❌ Failed to generate schema dump:', error)
    throw error
  }
}

gh.generatorHandler({
  onManifest() {
    return {
      defaultOutput: '../generated',
      prettyName: 'SQL Schema Generator',
      requiresEngines: [],
    }
  },

  async onGenerate(options) {
    await generateSqlSchema({
      generator: {
        output: options?.generator?.output ? { value: options.generator.output.value || '' } : undefined,
      },
    })
  },
})
