/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as protectedLayoutRouteImport } from "./routes/(protected)/layout"
import { Route as authLayoutRouteImport } from "./routes/(auth)/layout"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as authRegisterRouteImport } from "./routes/(auth)/register"
import { Route as authLoginRouteImport } from "./routes/(auth)/login"
import { Route as protectedDashboardIndexRouteImport } from "./routes/(protected)/dashboard/index"
import { Route as protectedDashboardSettingsRouteImport } from "./routes/(protected)/dashboard/settings"
import { Route as protectedDashboardProfileRouteImport } from "./routes/(protected)/dashboard/profile"

const protectedLayoutRoute = protectedLayoutRouteImport.update({
  id: "/(protected)",
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: "/(auth)",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => authLayoutRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => authLayoutRoute,
} as any)
const protectedDashboardIndexRoute = protectedDashboardIndexRouteImport.update({
  id: "/dashboard/",
  path: "/dashboard/",
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedDashboardSettingsRoute = protectedDashboardSettingsRouteImport.update({
  id: "/dashboard/settings",
  path: "/dashboard/settings",
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedDashboardProfileRoute = protectedDashboardProfileRouteImport.update({
  id: "/dashboard/profile",
  path: "/dashboard/profile",
  getParentRoute: () => protectedLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof authLoginRoute
  "/register": typeof authRegisterRoute
  "/dashboard/profile": typeof protectedDashboardProfileRoute
  "/dashboard/settings": typeof protectedDashboardSettingsRoute
  "/dashboard": typeof protectedDashboardIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof authLoginRoute
  "/register": typeof authRegisterRoute
  "/dashboard/profile": typeof protectedDashboardProfileRoute
  "/dashboard/settings": typeof protectedDashboardSettingsRoute
  "/dashboard": typeof protectedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/(auth)": typeof authLayoutRouteWithChildren
  "/(protected)": typeof protectedLayoutRouteWithChildren
  "/(auth)/login": typeof authLoginRoute
  "/(auth)/register": typeof authRegisterRoute
  "/(protected)/dashboard/profile": typeof protectedDashboardProfileRoute
  "/(protected)/dashboard/settings": typeof protectedDashboardSettingsRoute
  "/(protected)/dashboard/": typeof protectedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/register"
    | "/dashboard/profile"
    | "/dashboard/settings"
    | "/dashboard"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/register"
    | "/dashboard/profile"
    | "/dashboard/settings"
    | "/dashboard"
  id:
    | "__root__"
    | "/"
    | "/(auth)"
    | "/(protected)"
    | "/(auth)/login"
    | "/(auth)/register"
    | "/(protected)/dashboard/profile"
    | "/(protected)/dashboard/settings"
    | "/(protected)/dashboard/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLayoutRoute: typeof authLayoutRouteWithChildren
  protectedLayoutRoute: typeof protectedLayoutRouteWithChildren
}

declare module "@tanstack/solid-router" {
  interface FileRoutesByPath {
    "/(protected)": {
      id: "/(protected)"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof protectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(auth)": {
      id: "/(auth)"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(auth)/register": {
      id: "/(auth)/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authLayoutRoute
    }
    "/(auth)/login": {
      id: "/(auth)/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authLayoutRoute
    }
    "/(protected)/dashboard/": {
      id: "/(protected)/dashboard/"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof protectedDashboardIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    "/(protected)/dashboard/settings": {
      id: "/(protected)/dashboard/settings"
      path: "/dashboard/settings"
      fullPath: "/dashboard/settings"
      preLoaderRoute: typeof protectedDashboardSettingsRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    "/(protected)/dashboard/profile": {
      id: "/(protected)/dashboard/profile"
      path: "/dashboard/profile"
      fullPath: "/dashboard/profile"
      preLoaderRoute: typeof protectedDashboardProfileRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface protectedLayoutRouteChildren {
  protectedDashboardProfileRoute: typeof protectedDashboardProfileRoute
  protectedDashboardSettingsRoute: typeof protectedDashboardSettingsRoute
  protectedDashboardIndexRoute: typeof protectedDashboardIndexRoute
}

const protectedLayoutRouteChildren: protectedLayoutRouteChildren = {
  protectedDashboardProfileRoute: protectedDashboardProfileRoute,
  protectedDashboardSettingsRoute: protectedDashboardSettingsRoute,
  protectedDashboardIndexRoute: protectedDashboardIndexRoute,
}

const protectedLayoutRouteWithChildren = protectedLayoutRoute._addFileChildren(
  protectedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLayoutRoute: authLayoutRouteWithChildren,
  protectedLayoutRoute: protectedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
