// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"
import { defineConfig } from "prisma/config"

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Provide a default value for CI/CD environments where the database URL is not set
    // This allows prisma generate to run without connecting to the database
    url: process.env.DATABASE_URL ?? "postgresql://postgres:postgres@localhost:5432/effectify",
  },
})
